name: simple_moment
description: A simple implementation of the Moment.js features for relative time.
version: 0.1.1
author: rinukkusu <rinukkusu@auen.land>
homepage: https://github.com/rinukkusu

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0